version: '3.9'

services:
  fsm_bot:
    container_name: FsmBot
    image: fsm_bot
    build: .
    env_file:
      - .env  # Ensure this file exists in the same directory and contains BOT_TOKEN
    volumes:
      - logs:/path/inside/container
    # restart: on-failure

volumes:
  logs:

